version: "3"

services:
  core:
    build: ./core
    volumes:
      - ./core
    ports:
      - "5022:22"
  ui:
    build: ./ui
    volumes:
    - ./ui/src:/app
    ports:
      - 5000:80
    depends_on:
      - core
  test:
    image: python:3.7
    command: curl ui -o output.txt --connect-timeout 10 --max-time 10
    depends_on:
      - core
      - ui

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs