version: "3"

services:
  core:
    build: ./core
    restart: unless-stopped
    volumes:
      - ./core
    ports:
      - "5022:22"
  ui:
    build: ./ui
    restart: unless-stopped
    volumes:
      - ./ui/src/static:/app/static
      - ./ui/src/templates:/app/templates
      - ./ui/src/app.py:/app/app.py
    ports:
      - 5000:80
    depends_on:
      - core
  test:
    container_name: wait-for-it
    build: ./test
    restart: "no"
    command: -s -t 30 ui:80 -- bash -c "curl ui -o output.txt && echo Docker-test passed"
    depends_on:
      - core
      - ui

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs