version: "3"

services:
  core:
    build: ./core
    volumes:
      - ./core
    ports:
      - "5022:22"
  ui:
    build: ./ui
    volumes:
    - ./ui:/app
    ports:
      - 5000:80
    depends_on:
      - core

