version: "3"


services:
  core:
    build: ./core
    restart: unless-stopped
    volumes:
      - ./core
    ports:
      - "5022:22"
  ui:
    build: ./ui
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
    volumes:
      - ./ui/src/static:/app/static
      - ./ui/src/templates:/app/templates
      - ./ui/src/app.py:/app/app.py
      - ./ui/src/config.py:/app/config.py
      - ./ui/src/cert.py:/app/cert.py
    ports:
      - "443:443"
    depends_on:
      - core
    entrypoint: "python app.py"
  test:
    container_name: wait-for-it
    build: ./test
    restart: "no"
    command: -s -t 30 ui:443  -- bash -c "curl https://ui -o output.txt && echo Docker-test passed"
    depends_on:
      - ui

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs